# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MSH4thOfJuly' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MSH4thOfJuly
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  target 'MSH4thOfJulyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MSH4thOfJulyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
